language: node_js
node_js:
  - node
sudo: false
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: gHn0d5tMRF5HJzTjiAjX9sVABwG2N1QniOLzMeH2tTfNshqzsiZ8Yrn0N/OAsJqqXVzVg3Du2bqqBKkSWBpxdTRyPEOhNHHXE+X8XjByCQlKFEWHL7l3GUE4ntNzz3xT6rht5Po7C148HgAxBVHsMw7j3KQ4rzOpKllb8rlNO1Ez843XVBdsTYNSuK8PHueallA8h07kTxnog5OX/4BZghj3Bd8bbrD9D9Nvk8KUOYCa8b2hKjcZ45uZo52c0EjclFz3aMtFvSXyYCyAYWJE1Dmo/FDW5MbrYX/ejT4oxITrfIDMWqlRrdpR6r3xmkemU12OM6EVAQU99ZpYx02YbUOmRXL7dVOaZGoIBRq06TI566WUvTdLHDYHtsVgnPJkCdatNAbgxtLwzyNCFqjTNtdgFH036vHlYWDl94n5QppO3/lH1CdEa/brDDko4WOOUvynIsPmUJNgJsPrefIvNjeBFxI2nhcW0BPiZ5ycfNCC7F3HQr936eidF/AuLLL1d+CHH5NGZNXS3GDdAnO1OFekyCZoKO9PPg5OgVL48reCi9EjsY5H1ckaxeLO63vRhoqgxvcezHCSVNMyGwiQOzFR8ed6HqKFpNMPRxaY1fAJ6sEP4Y9r9T2Ldc27W2RT0WBOXvJHgEWySIrRMtHP038K7C5Cn+XMfuTAciLMxcU=
  app: devopsnapratica-pipeline
  edge: true
